// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"backend/config"
	"backend/db"
	"backend/handler"
	"backend/repository"
	"backend/router"
	"backend/service"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp(configPath string) (*gin.Engine, error) {
	configConfig := config.LoadConfig(configPath)
	gormDB, err := db.NewMySQL(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	engine := router.SetupRouter(configConfig, userHandler)
	return engine, nil
}

// wire.go:

var handlerSet = wire.NewSet(handler.NewUserHandler)

var serviceSet = wire.NewSet(service.NewUserService)

var repositorySet = wire.NewSet(repository.NewUserRepository)

var dbSet = wire.NewSet(db.NewMySQL)

var routerSet = wire.NewSet(router.SetupRouter)

var configSet = wire.NewSet(config.LoadConfig)

var SuperSet = wire.NewSet(
	handlerSet,
	serviceSet,
	repositorySet,
	dbSet,
	routerSet,
	configSet,
)
